name: deploy.yaml

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:qemu-v8.1.5
    - uses: docker/setup-buildx-action@v3
    - uses: actions/checkout@v4
    - uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        target: prod
        tags: ghcr.io/${{ github.repository }}:latest
        labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}